name=RaceDisplay
version=1.2.7
author=Francesco Troianiello <direzione@ehorizon.it>
maintainer=Francesco Troianiello <direzione@ehorizon.it>
sentence=Libreria per la gestione di display LED per motorsport (matrici, PIT, semaforo).
paragraph=Supporta bandiere, SC/VSC, starting procedure, PIT, animazioni non bloccanti.
category=Display
url=https://github.com/franzisco29/RaceDisplay
architectures=*
includes = FastLED.h